# 定义工作流名称
name: CI/CD Pipeline

# 触发工作流的事件
on:
  push:
    branches:
      - main

# 定义工作流中的任务
jobs:
  build:
    # 指定运行环境
    runs-on: ubuntu-latest

    # 定义任务步骤
    steps:
    - name: Checkout code
      # 使用actions/checkout@v2插件检出代码
      uses: actions/checkout@v2

    - name: Set up JDK 17
      # 使用actions/setup-java@v2插件设置JDK版本为17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      # 使用Maven构建项目
      run: |
        mvn clean
        mvn -B package --file pom.xml

    - name: Build Docker image
      # 构建Docker镜像
      run: |
        docker build -t springboot_action:${{ github.sha }} .

    - name: Login to Alibaba Cloud Container Registry
      # 登录到阿里云镜像服务
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin registry.cn-hangzhou.aliyuncs.com

    - name: Tag Docker image
      # 为Docker镜像打标签
      run: |
        docker tag springboot_action:${{ github.sha }} registry.cn-hangzhou.aliyuncs.com/yingzi_666/action_test:${{ github.sha }}

    - name: Push Docker image
      # 推送Docker镜像到阿里云镜像服务
      run: |
        docker push registry.cn-hangzhou.aliyuncs.com/yingzi_666/action_test:${{ github.sha }}

    - name: Deploy to Cloud Server
      # 使用ssh-action插件部署到云服务器
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin registry.cn-hangzhou.aliyuncs.com
          docker pull registry.cn-hangzhou.aliyuncs.com/yingzi_666/action_test:${{ github.sha }}
          docker stop springboot_action || true
          docker rm springboot_action || true
          docker run -d --name springboot_action -p 8094:8094 registry.cn-hangzhou.aliyuncs.com/yingzi_666/action_test:${{ github.sha }}