# 定义工作流名称
name: CI/CD Pipeline

# 触发工作流的事件
on:
  push:
    branches:
      - main

# 定义工作流中的任务
jobs:
  build:
    # 指定运行环境
    runs-on: ubuntu-latest

    # 定义任务步骤
    steps:
    - name: Checkout code
      # 使用actions/checkout@v2插件检出代码
      uses: actions/checkout@v2

    - name: Set up JDK 17
      # 使用actions/setup-java@v2插件设置JDK版本为17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      # 使用Maven构建项目
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      # 构建Docker镜像
      run: |
        docker build -t your-dockerhub-username/your-repo-name:${{ github.sha }} .

    - name: Login to Docker Hub
      # 登录Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      # 推送Docker镜像到Docker Hub
      run: |
        docker push your-dockerhub-username/your-repo-name:${{ github.sha }}

    - name: Deploy to Cloud Server
      # 使用ssh-action插件部署到云服务器
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull your-dockerhub-username/your-repo-name:${{ github.sha }}
          docker stop your-container-name || true
          docker rm your-container-name || true
          docker run -d --name your-container-name -p 8080:8080 your-dockerhub-username/your-repo-name:${{ github.sha }}